name: Build Docker image

on: 
  push:
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: evgsentrium
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: |
          ghcr.io/evgsentrium/hello
    
    - name: Print outputs
      run: |
        echo "${{ steps.meta.outputs.labels }}" && \
        echo "\n\n" && \
        echo "${{ steps.meta.outputs.tags }}"

    - name: Build and push Docker images
      id: push
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        push: true
        tags: ghcr.io/evgsentrium/hello:latest

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ghcr.io/evgsentrium/hello:latest
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true